import type { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Horaris • Llibreria Domingo • Des de 1943',
    description: 'Generated by create next app',
}

export default function TimeTable() {
    return (
        <section className="page-section cta">
            <div className="container">
                <div className="row">
                    <div className="col-xl-9 mx-auto">
                        <div className="cta-inner text-center rounded">
                            <h2 className="section-heading mb-5">
                                <span className="section-heading-upper">Vingui a veure&#39;ns</span>
                                <span className="section-heading-lower">El nostre horari</span>
                            </h2>
                            <ul className="list-unstyled list-hours mb-5 text-left mx-auto">
                                <li className="list-unstyled-item list-hours-item d-flex">
                                    Dilluns
                                    <span className="ml-auto">9:00 a 13:00 - 16:30 a 20:00</span>
                                </li>
                                <li className="list-unstyled-item list-hours-item d-flex">
                                    Dimarts
                                    <span className="ml-auto">9:00 a 13:00 - 16:30 a 20:00</span>
                                </li>
                                <li className="list-unstyled-item list-hours-item d-flex">
                                    Dimecres
                                    <span className="ml-auto">9:00 a 13:00 - 16:30 a 20:00</span>
                                </li>
                                <li className="list-unstyled-item list-hours-item d-flex">
                                    Dijous
                                    <span className="ml-auto">9:00 a 13:00 - 16:30 a 20:00</span>
                                </li>
                                <li className="list-unstyled-item list-hours-item d-flex">
                                    Divendres
                                    <span className="ml-auto">9:00 a 13:00 - 16:30 a 20:00</span>
                                </li>
                                <li className="list-unstyled-item list-hours-item d-flex">
                                    Dissabte
                                    <span className="ml-auto">9:30 a 13:00</span>
                                </li>
                                <li className="list-unstyled-item list-hours-item d-flex">
                                    Diumenge
                                    <span className="ml-auto">Tancat</span>
                                </li>
                            </ul>
                            <p className="address mb-5">
                                <em>
                                    <strong>Carrer Major, 16</strong>
                                    <br />
                                    43201 Reus (Tarragona)
                                </em>
                            </p>
                            <p className="mb-0">
                                <small>
                                    <em>Truqui&#39;ns</em>
                                </small>
                                <br />
                                977 34 12 53
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    )
}
